# Generated by Django 6.0.1 on 2026-02-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branch", "0001_initial"),
        ("products", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="branch.branch",
            ),
        ),
    ]
