# Generated by Django 6.0.1 on 2026-02-20 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_branch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="item_code",
            new_name="product_code",
        ),
    ]
