# Generated by Django 6.0.1 on 2026-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "branch_code",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=15)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
    ]
