# Generated by Django 6.0.1 on 2026-02-05 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branch", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_transactions",
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales transaction",
                "verbose_name_plural": "Sales transactions",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_consumed",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumptions",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "sales_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="sales.salestransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory consumption",
                "verbose_name_plural": "Inventory consumptions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
