# Generated by Django 6.0.1 on 2026-02-18 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salestransaction",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_transactions",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="quantity_sold",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
