# Generated by Django 6.0.1 on 2026-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_salestransaction_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryconsumption",
            name="quantity_consumed",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
