# Generated by Django 6.0.1 on 2026-03-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_item_code_product_product_code'),
        ('sales', '0003_alter_inventoryconsumption_quantity_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales_transactions', to='products.product'),
            preserve_default=False,
        ),
    ]
