# Generated by Django 6.0.1 on 2026-02-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branch", "0001_initial"),
        ("inventory", "0001_initial"),
        ("warehouse", "0002_warehouserequest_warehousetransaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("branch_to_branch", "Branch to Branch"),
                            ("branch_to_warehouse", "Branch to Warehouse"),
                            ("warehouse_to_branch", "Warehouse to Branch"),
                            ("warehouse_to_warehouse", "Warehouse to Warehouse"),
                        ],
                        help_text="Automatically determined from from/to locations",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("dispatched", "Dispatched"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_from",
                        to="branch.branch",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_from",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_to",
                        to="branch.branch",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_to",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer",
                "verbose_name_plural": "Transfers",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Requested/expected quantity",
                        max_digits=14,
                    ),
                ),
                (
                    "dispatched_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Actual quantity dispatched",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Actual quantity received",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Received quantity - dispatched quantity",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transfers.transfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer item",
                "verbose_name_plural": "Transfer items",
                "ordering": ["transfer", "inventory_item"],
                "unique_together": {("transfer", "inventory_item")},
            },
        ),
    ]
