# Generated by Django 6.0.1 on 2026-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferitem",
            name="dispatched_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual quantity dispatched",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transferitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, help_text="Requested/expected quantity", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="transferitem",
            name="received_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual quantity received",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transferitem",
            name="variance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Received quantity - dispatched quantity",
                max_digits=14,
                null=True,
            ),
        ),
    ]
