# Generated by Django 6.0.1 on 2026-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_alter_transferitem_dispatched_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes or reason for this transfer.'),
        ),
    ]
