# Generated by Django 6.0.1 on 2026-08-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0012_alter_inventoryitem_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentAdvice',
            fields=[
            ],
            options={
                'verbose_name': 'Replenishment advice',
                'verbose_name_plural': 'Replenishment advice',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.branchinventory',),
        ),
    ]
