# Generated by Django 6.0.1 on 2026-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    atomic = False

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
