# Generated by Django 6.0.1 on 2026-02-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branch", "0001_initial"),
        ("inventory", "0001_initial"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if status is rejected",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_requests",
                        to="branch.branch",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse request",
                "verbose_name_plural": "Warehouse requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("inward", "Inward"),
                            ("outward", "Outward"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Positive for inward/adjustment increase, negative for outward/adjustment decrease",
                        max_digits=14,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (e.g., 'WarehouseRequest', 'Transfer', 'GoodsReceipt')",
                        max_length=100,
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_transactions",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse transaction",
                "verbose_name_plural": "Warehouse transactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Current stock quantity in warehouse",
                        max_digits=14,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Storage location within warehouse (e.g., 'Aisle 3, Shelf B')",
                        max_length=255,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_inventories",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_inventories",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse inventory",
                "verbose_name_plural": "Warehouse inventories",
                "ordering": ["warehouse", "inventory_item"],
                "unique_together": {("warehouse", "inventory_item")},
            },
        ),
        migrations.CreateModel(
            name="WarehouseRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_request_items",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "warehouse_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.warehouserequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse request item",
                "verbose_name_plural": "Warehouse request items",
                "ordering": ["warehouse_request", "inventory_item"],
                "unique_together": {("warehouse_request", "inventory_item")},
            },
        ),
    ]
