# Generated by Django 6.0.1 on 2026-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_warehouserequest_warehousetransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouseinventory",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current stock quantity in warehouse",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="warehouserequestitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="warehousetransaction",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Positive for inward/adjustment increase, negative for outward/adjustment decrease",
                max_digits=14,
            ),
        ),
    ]
