# Generated by Django 6.0.1 on 2026-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehouseinventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseinventory',
            name='minimum_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum stock level; alerts when quantity falls below this.', max_digits=14),
        ),
    ]
