# Generated by Django 6.0.1 on 2026-02-26 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentdocument",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="paymentdocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="vendorinvoice",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="vendorinvoice",
            name="vendor",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="PaymentDocument",
        ),
        migrations.DeleteModel(
            name="VendorInvoice",
        ),
    ]
