# Generated by Django 6.0.1 on 2026-04-02 22:19

from django.db import migrations, models


def populate_emails(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(models.Q(email='') | models.Q(email__isnull=True)):
        user.email = f"user_{user.pk}@example.com"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RunPython(populate_emails),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
