# Generated by Django 6.0.1 on 2026-04-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_purchaser_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_own_profile', 'Can view own profile')]},
        ),
    ]
