# Generated by Django 6.0.1 on 2026-02-05 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branch", "0001_initial"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Unit of measure",
                "verbose_name_plural": "Units of measure",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("barcode", models.CharField(blank=True, max_length=100, unique=True)),
                ("sku", models.CharField(blank=True, db_index=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "stock_quantity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "minimum_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=4, default=0, max_digits=14
                    ),
                ),
                (
                    "tracking_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="branch.branch",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory item",
                "verbose_name_plural": "Inventory items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product",
                    models.OneToOneField(
                        help_text="The finished product this BOM defines.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill of materials",
                "verbose_name_plural": "Bills of materials",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("increase", "Increase"),
                            ("decrease", "Decrease"),
                            ("correction", "Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to="branch.branch",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustments",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock adjustment",
                "verbose_name_plural": "Stock adjustments",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StockCycleCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "counted_quantity",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Counted quantity - system quantity at time of count.",
                        max_digits=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_counts",
                        to="branch.branch",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_counts",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_counts",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock cycle count",
                "verbose_name_plural": "Stock cycle counts",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.bom",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_components",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM item",
                "verbose_name_plural": "BOM items",
                "ordering": ["bom", "inventory_item"],
                "unique_together": {("bom", "inventory_item")},
            },
        ),
    ]
