# Generated by Django 6.0.1 on 2026-02-18 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bom",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="The finished product this BOM defines.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boms",
                to="products.product",
            ),
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="inventory.inventorycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory category",
                "verbose_name_plural": "Inventory categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="inventory.inventorycategory",
            ),
        ),
    ]
