# Generated by Django 6.0.1 on 2026-02-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_bom_product_inventorycategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_category_items",
                to="inventory.inventorycategory",
                verbose_name="Sub Category",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"parent_category__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_items",
                to="inventory.inventorycategory",
                verbose_name="Category",
            ),
        ),
    ]
