# Generated by Django 6.0.1 on 2026-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_inventoryitem_sub_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="historical_usage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                help_text="Historical usage used for planning (optional).",
                max_digits=14,
            ),
        ),
    ]
