# Generated by Django 6.0.1 on 2026-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_inventoryitem_historical_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="historical_usage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Historical usage used for planning (optional).",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="minimum_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="stock_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="stockadjustment",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="stockcyclecount",
            name="counted_quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="stockcyclecount",
            name="variance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Counted quantity - system quantity at time of count.",
                max_digits=14,
            ),
        ),
    ]
