# Generated by Django 6.0.1 on 2026-02-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branch", "0001_initial"),
        ("inventory", "0005_alter_bomitem_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="historical_usage",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="minimum_threshold",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="stock_quantity",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="tracking_frequency",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="warehouse",
        ),
        migrations.CreateModel(
            name="BranchInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "minimum_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=14
                    ),
                ),
                (
                    "historical_usage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Historical usage used for planning (optional).",
                        max_digits=14,
                    ),
                ),
                (
                    "tracking_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_inventories",
                        to="branch.branch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branch_inventories",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch inventory",
                "verbose_name_plural": "Branch inventories",
                "ordering": ["branch", "item"],
                "unique_together": {("branch", "item")},
            },
        ),
        migrations.AlterField(
            model_name="inventorycategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="inventorycategory",
            unique_together={("name", "parent_category")},
        ),
    ]
