# Generated by Django 6.0.1 on 2026-02-27 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_inventoryitem_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="section",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"parent_category__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="section_items",
                to="inventory.inventorycategory",
                verbose_name="Section",
            ),
        ),
        migrations.AlterField(
            model_name="inventorycategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category for this category. set null for sections",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="inventory.inventorycategory",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_items",
                to="inventory.inventorycategory",
                verbose_name="Category",
            ),
        ),
    ]
