# Generated by Django 6.0.1 on 2026-03-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_inventoryitem_sub_category_and_more'),
        ('products', '0004_rename_item_code_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(default=1, help_text='The finished product this BOM defines.', on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='products.product'),
            preserve_default=False,
        ),
    ]
