# Generated by Django 6.0.1 on 2026-03-24 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_bom_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcyclecount',
            name='counted_by',
            field=models.ForeignKey(blank=True, help_text='User who performed this count.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
