# Generated by Django 6.0.1 on 2026-03-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_counted_by_to_stockcyclecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Factor to convert BOM quantity to inventory base unit. e.g., if BOM says 250g and item is tracked in kg, factor = 0.001 (250g × 0.001 = 0.25kg).', max_digits=14),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text="Unit of this component in the BOM (e.g., 250g). Leave blank to use the item's base unit.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='inventory.unitofmeasure'),
        ),
    ]
