# Generated by Django 6.0.1 on 2026-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_bomitem_conversion_factor_bomitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
