# Generated by Django 6.0.1 on 2026-04-29 13:55

import hashlib

from django.db import migrations, models
from django.db.models.functions import Length


def _generate_unique_barcode(item_id, old_barcode, existing_barcodes):
    """
    Build deterministic unique barcode with max length 8.
    Format: 'BC' + 6 hex chars.
    """
    attempt = 0
    while True:
        source = f"{item_id}|{old_barcode}|{attempt}"
        digest = hashlib.sha1(source.encode("utf-8")).hexdigest().upper()
        candidate = f"BC{digest[:6]}"
        if candidate not in existing_barcodes:
            return candidate
        attempt += 1


def rewrite_long_barcodes(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")

    existing_barcodes = set(
        InventoryItem.objects.exclude(barcode__isnull=True)
        .exclude(barcode="")
        .values_list("barcode", flat=True)
    )

    long_items = (
        InventoryItem.objects.annotate(barcode_len=Length("barcode"))
        .filter(barcode_len__gt=8)
        .only("id", "barcode")
        .order_by("id")
    )

    for item in long_items.iterator(chunk_size=500):
        old_barcode = item.barcode or ""
        new_barcode = _generate_unique_barcode(item.id, old_barcode, existing_barcodes)
        item.barcode = new_barcode
        item.save(update_fields=["barcode"])
        existing_barcodes.add(new_barcode)


def noop_reverse(apps, schema_editor):
    # Intentionally irreversible: original long barcode values are not preserved.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_branchinventory_updated_at_inventoryitem_updated_at'),
    ]

    operations = [
        migrations.RunPython(rewrite_long_barcodes, noop_reverse),
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
