# Generated by Django 6.0.1 on 2026-02-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("dispatch", "Dispatch"),
                            ("receive", "Receive"),
                            ("cancel", "Cancel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model (e.g., 'PurchaseOrder', 'Demand')",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of the affected object", null=True
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the object",
                        max_length=255,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON field storing before/after values for updates",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent string", max_length=255
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the action"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log",
                "verbose_name_plural": "Audit logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="reports_aud_timesta_5ddcef_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="reports_aud_user_id_109722_idx",
                    ),
                    models.Index(
                        fields=["model_name", "-timestamp"],
                        name="reports_aud_model_n_5d0f84_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="reports_aud_action__d531de_idx",
                    ),
                ],
            },
        ),
    ]
