# Generated by Django 6.0.1 on 2026-02-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_auditlog_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of the affected object (can be string or integer)",
                max_length=255,
            ),
        ),
    ]
