# Generated by Django 6.0.1 on 2026-02-05 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branch", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand item",
                "verbose_name_plural": "Demand items",
                "ordering": ["demand", "priority", "inventory_item"],
            },
        ),
        migrations.CreateModel(
            name="Demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Requested quantity for the primary item (if set).",
                        max_digits=14,
                    ),
                ),
                (
                    "minimum_threshold",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Snapshot of minimum threshold at demand time.",
                        max_digits=14,
                    ),
                ),
                (
                    "historical_usage",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Snapshot of historical usage used to justify this demand.",
                        max_digits=14,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_demands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demands",
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand",
                "verbose_name_plural": "Demands",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
