# Generated by Django 6.0.1 on 2026-02-05 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("demands", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_demands",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="demand",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_demands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demanditem",
            name="demand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="demands.demand",
            ),
        ),
        migrations.AddField(
            model_name="demanditem",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="demand_items",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="demanditem",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="demand_items",
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="demanditem",
            unique_together={("demand", "inventory_item")},
        ),
    ]
