# Generated by Django 6.0.1 on 2026-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
