# Generated by Django 6.0.1 on 2026-02-25 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0003_alter_demand_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demand",
            name="historical_usage",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="minimum_threshold",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="requested_quantity",
        ),
    ]
