# Generated by Django 6.0.1 on 2026-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0005_alter_demand_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demanditem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
