# Generated by Django 6.0.1 on 2026-02-26 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0006_alter_demanditem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demand",
            name="inventory_item",
        ),
    ]
