# Generated by Django 6.0.1 on 2026-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0007_remove_demand_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanditem',
            name='approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approved quantity (for partial approval). Null = full quantity approved.', max_digits=14, null=True),
        ),
    ]
