# Generated by Django 6.0.1 on 2026-02-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
