# Generated by Django 6.0.1 on 2026-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_alter_purchaseorder_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="total_received_quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="goodsreceiptitem",
            name="variance",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Received quantity - expected quantity.",
                max_digits=14,
            ),
        ),
    ]
