# Generated by Django 6.0.1 on 2026-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0003_alter_goodsreceipt_total_received_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceipt",
            name="total_received_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="goodsreceiptitem",
            name="expected_quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="goodsreceiptitem",
            name="received_quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="goodsreceiptitem",
            name="variance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Received quantity - expected quantity.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
