# Generated by Django 6.0.1 on 2026-02-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0007_remove_demand_inventory_item"),
        ("payments", "0002_remove_paymentdocument_payment_and_more"),
        ("purchases", "0004_alter_goodsreceipt_total_received_quantity_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReceiptImage",
            new_name="ReceivedItemImage",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="demand",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="goodsreceipt",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="inventory_item",
        ),
        migrations.AlterModelOptions(
            name="receiveditemimage",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Received item image",
                "verbose_name_plural": "Received item images",
            },
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="demand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipts",
                to="demands.demand",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PurchaseReceiptImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.FileField(blank=True, upload_to="purchase_receipts/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_receipt_images",
                        to="demands.demand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase receipt image",
                "verbose_name_plural": "Purchase receipt images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
        migrations.DeleteModel(
            name="PurchaseOrder",
        ),
        migrations.DeleteModel(
            name="PurchaseOrderItem",
        ),
    ]
