# Generated by Django 6.0.1 on 2026-04-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_vendor_purchaseorder_goodsreceipt_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='image_file',
            field=models.FileField(blank=True, help_text='Optional goods receipt image proof.', null=True, upload_to='goods_receipts/'),
        ),
    ]
